#!/usr/bin/env bash
# A script that displays 'To infinity and beyond' indefinitely
# Requirement: In between each iteration of the loop2

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
