#!/usr/bin/env bash
# A script display the contents of file `/etc/passwd`
#   It only display the username, user id, and user home directory path

myfile="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$myfile"
