#!/usr/bin/env bash
# A script that displays content of the current directory in a list format
# It only displays the part of the name after the first dash

mylist=$(ls)

for i in $mylist; do
  echo "$i" | cut -d '-' -f2
done
